name: feature-01 CI
run-name: ${{ github.actor }} is integrating feature-01
on:
  push:
    branches:
      - feature-01
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secret.PUSH_MAIN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup git user
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test project
        run: yarn run test
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git merge feature-01
          git push origin main
