name: feature-01 CI
run-name: ${{ github.actor }} is integrating feature-01
on:
  push:
    branches:
      - feature-01
jobs:
  ci-feature-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup git user
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test project
        run: yarn run test
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git merge feature-01
          git push origin main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: ci-feature-01
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup git user
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: PUBLIC_URL=/${{ github.event.repository.name }} yarn run build
      - name: Deploy gh-pages
        run: |
          cd ./build
          git init -b gh-pages
          git remote add -t gh-pages origin \
          https://git:${{ github.token }}@github.com/${{ github.repository }}.git
          git fetch -u origin gh-pages:gh-pages
          git add .
          git commit -m "${{ github.actor }} deploy"
          git push origin gh-pages -f
          cd ..
